### ISSUE TITLE
i cant display arrow

### ISSUE THREAD

**Issue by nda-cunh** [alexandregv/norminette-vim#3]
Bonjour, Je n'ai peut-être pas compris comment cela fonctionne mais je ne peux pas afficher les flèches sur la gauche par contre j'ai bien le menu Norminette en bas et j'ai bien mis la même configuration vim sur mon vimrc que dans le README

![Screenshot from 2022-08-23 21-00-26](https://user-images.githubusercontent.com/40312793/186243803-a5968cba-2840-4adb-a47e-33108d4676b3.png)

(J'ai aussi syntastic dont celui-ci fonctionne avec gcc)
ma configuration vim est ici si besoin:
https://gitlab.com/hydrasho/SupraVim

**Comment by nda-cunh** [comment]
Ok je crois que je viens de comprendre ce que c'est un linter, c'est la présence de syntastique qui m'a fait pensé qu'il faisait les flèches ^^

**Comment by nda-cunh** [comment]
update j'ai reussi à rajouté les fleches plus qu'a rajouté les petit message en bas de la ligne :)

**Comment by alexandregv** [comment]
Normalement elles y sont par défaut, le message aussi
Ta config doit changer ça je suppose (pas vérifié)

**Comment by nda-cunh** [comment]
du coup j'ai recrée un plugin vim pour avoir les fleches sur mon vim ^^
![Screenshot from 2022-08-26 00-50-52](https://user-images.githubusercontent.com/40312793/187508232-b6e1a7db-9906-4f4f-b31e-7354418aba3a.png)
merci quand meme :)

**Comment by alexandregv** [comment]
J'ai finalement trouvé l'origine du problème : lors d'une mise à jour de la norminette le format des messages a changé (`KO!` est devenu `Error!` et les numéros de ligne/colonne ont désormais du padding).

Je l'ai corrigé dans le commit 1a06bc1b4d44ae5b0b1956324071c05828f92583 :slightly_smiling_face:
