### ISSUE TITLE
Is there a way to toggle on/off the linter ?

### ISSUE THREAD

**Issue by Rz-Rz** [alexandregv/norminette-vim#5]
Everything is in the title.

**Comment by alexandregv** [comment]
If you want to disable it in the config, remove it from this array:
```diff
" Enable norminette-vim (and gcc)
-let g:syntastic_c_checkers = ['norminette', 'gcc']
+let g:syntastic_c_checkers = ['gcc']
```

If you meant a way to toggle it on the go, then there is no builtin feature in this plugin. However, Syntastic has a passive/active mode that you can toggle with a keymap. Check [this SO thread](https://stackoverflow.com/questions/20030603/vim-syntastic-how-to-disable-the-checker), it has multiple solutions.

**Comment by Rz-Rz** [comment]
Thank you for your response, this is my workaround : 
`nnoremap <silent>;s <cmd>:SyntasticToggleMode<cr>`
